
update_rate:                    100                             # spin rate of stem_tracking node, in hz
debug:                          1                               # if true (1) additional information will be printed, else set to false (0)
base_frame:                     /amigo/base_link                # frame we use to define stem and to show markers in rviz

#######################
# ROBOT CONFIG
#######################

use_leftarm:                    1                               # use left arm if true (1), else use right arm
robot_description_rosparam:     /amigo/robot_description        # amigo urdf model gets loaded from this rosparam
root_link:                      base_link                       # start of kinematic chain we are controlling
left_end_link:                  grippoint_left                  # end of kinematic chain we are controlling, if use_leftarm
right_end_link:                 grippoint_right                 # end of kinematic chain we are controlling, if not use_leftarm
up_to_date_threshold:           0.5                             # consider robot status up to date if measurement received within passed x sec
initial_pose:                                                   # pose used as preposition, length should be equal to the number of joints in kinematic chain
    - {q: 0.1}
    - {q: -0.1}
    - {q: -0.6}
    - {q: 0.0}
    - {q: 1.8}
    - {q: -0.1}
    - {q: 0.4}
    - {q: 0.0}

#######################
# WHISKER CONFIG
#######################

n_whiskers:                     10                              # total numbers of whiskers in gripper
whisker_length:                 0.05                            # length of a single whisker, in meters
gripper_diameter:               0.1                             # diameter of gripper at whisker-root, in meters
max_whisker_force:              1.0                             # force applied to the stem by a fully bended (90 degrees) whisker

#######################
# TOMATO STEM CONFIG
#######################

stem_nodes:                                                     # stem nodes, defined in root_link
    - {x: 0.55, y: 0.35, z: 0.6}
    - {x: 0.5, y: 0.35, z: 0.9}
    - {x: 0.55, y: 0.4, z: 1.2}
    - {x: 0.5, y: 0.55, z: 1.4}

##########################
# TRACKING CONTROL CONFIG
##########################

max_z_dot:                      0.5                             # max gripper velocity in vertical direction during stem tracking (m/s)
tilt_with_stem:                 1                               # if true (1) tilt gripper based on local derivative of stem
