
update_rate:                    100                             # spin rate of stem_tracking node, in hz
base_frame:                     /amigo/base_link                # frame we use to define stem and to show markers in rviz

#######################
# ROBOT CONFIG
#######################

robot_urdf_file:                /home/amigo/ros/hydro/system/src/amigo_description/urdf/amigo.urdf
use_leftarm:                    1                               # use left arm if true (1), else use right arm
robot_description_rosparam:     /amigo/robot_description        # amigo urdf model gets loaded from this rosparam
root_link:                      base_link                       # start of kinematic chain we are controlling
left_end_link:                  grippoint_left                  # end of kinematic chain we are controlling, if use_leftarm
right_end_link:                 grippoint_right                 # end of kinematic chain we are controlling, if not use_leftarm
joints_up_to_date_threshold:    0.1                            # consider joints status up to date if measurement received
                                                                 # within passed x sec
whiskers_up_to_date_threshold:  0.1            # consider whisker status up to date if measurement received
                                                # within passed x sec
pressure_sensors_up_to_date_threshold:  0.1    # consider pressure sensors status up to date if measurement received
                                                # within passed x sec
initial_pose:               # pose used as preposition, length should be equal to the number
    - {q: 0.1}               # of joints in kinematic chain
    - {q: -0.1}
    - {q: -0.6}
    - {q: 0.0}
    - {q: 1.8}
    - {q: -0.1}
    - {q: 0.4}
    - {q: 0.0}

#######################
# WHISKERGRIPPER CONFIG
#######################

n_seconds_for_initialization:	5.0             # number of seconds we take to average whisker and pressure sensor values during
                                                 # initialization (the average will be used as nominal value)

n_sec_for_moving_av:    4.0

whisker_coverage:                                                 # Angular 'piece of the pie' covered by a whisker in the xy plane
    - {min: 10, max: 65, n_whiskers: 2, grasp_check: 1}            # of the gripper. Positive is rotating x towards y. Direction of x
    - {min: 65, max: 110, n_whiskers: 2, grasp_check: 0}           # is zero. Unit: degrees between 0 and 360 (integers). The order is
    - {min: 100, max: 135, n_whiskers: 1, grasp_check: 0}          # the order at which the whisker values are stored in RobotStatus. If
    - {min: 135, max: 225, n_whiskers: 2, grasp_check: 0}          # a whisker is used to check whether the stem enters/leaves the gripper
    - {min: 225, max: 270, n_whiskers: 1, grasp_check: 0}          # grasp_check = 1
    - {min: 270, max: 300, n_whiskers: 2, grasp_check: 0}
    - {min: 300, max: 360, n_whiskers: 2, grasp_check: 1}

whisker_touched_normalized_threshold: 0.1      # Whisker deviations are normalized based on whisker_touched_max. We consider a whisker unit
                                                # touched when the normalized error is larger than this threshold

whisker_touched_madx:
    - {max: 2.01817}
    - {max: 1.34795}
    - {max: 1.36247}
    - {max: 1.53378}
    - {max: 1.16193}
    - {max: 0.40856}
    - {max: 2.45861}
    - {max: 0.952206}
    - {max: 0.534892}
    - {max: 1.06684}
    - {max: 0.825003}
    - {max: 1.79269}

whisker_touched_max:
	- {max: 2.01817}
	- {max: 1.34795}
	- {max: 2.83341}
	- max: 2.13553  w_4_max: 1.46022  w_5_max: 0.56652  w_6_max: 2.45861
	  
w_7_max: 1.06293  w_8_max: 0.792967  w_9_max: 2.00418  w_10_max: 1.94857  w_11_max: 2.94864

pressure_sensor_strip_coverage:      # Angular 'piece of the pie' covered by a single pressure sensor sensor in the xy plane of the gripper.
    - {min: 40, max: 140}             # Positive is rotating x towards y. Direction of x is zero. Unit: degrees between 0 and 360 (integers).
    - {min: 140, max: 220}
    - {min: 220, max: 320}

pressure_sensor_location:      # Angular location of the pressure sensors in the xy plane of the gripper. Positive
    - {ang: 70}                 # is rotating x towards y. Direction of x is zero. Unit: degrees between 0 and 360 (integers).
    - {ang: 110}                # The order is the order at which the pressure sensor values are stored in RobotStatus.
    - {ang: 180}
    - {ang: 250}
    - {ang: 295}

pressure_sensor_touched_normalized_threshold:  0.02   # Pressure sensor deviations are normalized based on pressure_sensor_max_touched. We consider
                                                       # a pressure sensor coverage touched when the normalized deviation is larger than this value

pressure_sensor_touched_max:
    - {max: 1.83575}
    - {max: 1.89297}
    - {max: 0.961392}
    - {max: 1.90908}
    - {max: 1.73179}
p_0_max: 1.83575  p_1_max: 1.91311  p_2_max: 1.08147  p_3_max: 1.91392  p_4_max: 1.77692

#######################
# WHISKER SIM CONFIG
#######################

whisker_length:                 0.03          # length of a single whisker, in meters (used only for sim)
gripper_diameter:               0.01           # diameter of gripper at whisker-root, in meters (used only for sim)

#######################
# TOMATO STEM CONFIG
#######################

lin_tan_d:                      0.1           # distance in z we use to calculate local linear tangent of stem
start_tracking_at_z:            0.53          # meters, defined in amigo base frame

stem_nodes:                                   # stem nodes, defined in root_link
#   - {x: 0.55, y: 0.35, z: 0.62}
#   - {x: 0.2, y: 0.6, z: 0.62}
    - {x: 0.55, y: 0.3, z: 1.0}
    - {x: 0.55, y: 0.3, z: 1.2}

##########################
# TRACKING CONTROL CONFIG
##########################

move_up_ref:                    0.001         # put xyz ref up (in direction of stem tangent) for x meters when moving
                                               # up (state FOLLOW)
tilt_with_stem:                 0             # if true (1) tilt gripper based on local derivative of stem
debug_ik_solver:                0             # if true (1) status of kdl ik solver will be printed
ik_vel_only:                    0             # if true (1) after initialization we only use kdl ik velocity solver, no
                                               # fk or ik position solvers
xyz_reached_threshold:          0.05          # if cartesian position error of the gripper in robot-status is below this
                                               # threshold position is considered reached
pos_reached_threshold:          0.01          # if absolute position error for each of the joints in robot-status is below
                                               # this threshold position is considered reached
straight_forward_ref:           0.001         # put xyz ref forward for x meters when asked moving forward (state GRASP)

##########################
# TRACKING MONITOR CONFIG
##########################

debug_state_par:                1             # if true (1) state will be printed every time it changes
find_max_touched_values:        1             # if true (1) robot will move to preposition and stay there while printing
                                               # the maximum values it knows for whiskers deflection for each whisker and
                                               # for pressure sensing for each pressure sensor

##########################
# VISUALIZATION CONFIG
##########################

buffer_size:                    100         # buffer size for rviz marker topic
touched_arrow_liftime:          0.02        # when whisker touched show an arrow for x seconds, set to -1.0 to show until
                                             # next msg
show_setpoint_lifetime:         0.02        # show cartesian setpoint and current pos of gripper for x seconds, set to
                                             # -1.0 to show until next msg
show_stem_tangent_lifetime:     3.0         # show estimated tangent of stem at current gripper pos for x seconds, set to
                                             # -1.0 to show until next msg
