
update_rate:                    100                             # spin rate of stem_tracking node, in hz
loglevel:                       1                               # if larger than zero additional information will be printed (currently only one loglevel implemented)
base_frame:                     /amigo/base_link                # frame we use to define stem and to show markers in rviz

#######################
# ROBOT CONFIG
#######################

robot_urdf_file:                /home/amigo/ros/hydro/system/src/amigo_description/urdf/amigo.urdf
use_leftarm:                    1                               # use left arm if true (1), else use right arm
robot_description_rosparam:     /amigo/robot_description        # amigo urdf model gets loaded from this rosparam
root_link:                      base_link                       # start of kinematic chain we are controlling
left_end_link:                  grippoint_left                  # end of kinematic chain we are controlling, if use_leftarm
right_end_link:                 grippoint_right                 # end of kinematic chain we are controlling, if not use_leftarm
up_to_date_threshold:           0.05                            # consider robot status up to date if measurement received within passed x sec
initial_pose:                                                   # pose used as preposition, length should be equal to the number of joints in kinematic chain
    - {q: 0.1}
    - {q: -0.1}
    - {q: -0.6}
    - {q: 0.0}
    - {q: 1.8}
    - {q: -0.1}
    - {q: 0.4}
    - {q: 0.0}

#######################
# WHISKER CONFIG
#######################

n_whiskers:                     10                              # total numbers of whiskers in gripper
whisker_length:                 0.05                            # length of a single whisker, in meters
gripper_diameter:               0.1                             # diameter of gripper at whisker-root, in meters
max_whisker_force:              1.0                             # force applied to the stem by a fully bended (90 degrees) whisker

#######################
# TOMATO STEM CONFIG
#######################

lin_tan_d:                      0.1                             # distance in z we use to calculate local linear tangent of stem
stem_nodes:                                                     # stem nodes, defined in root_link
    - {x: 0.55, y: 0.35, z: 0.5}
    - {x: 0.55, y: 0.35, z: 0.62}
    - {x: 0.5, y: 0.35, z: 0.9}
    - {x: 0.55, y: 0.4, z: 1.2}
    - {x: 0.5, y: 0.55, z: 1.4}

##########################
# TRACKING CONTROL CONFIG
##########################

max_z_dot:                      0.2                               # max gripper velocity in vertical direction during stem tracking (m/s)
tilt_with_stem:                 1                               # if true (1) tilt gripper based on local derivative of stem
debug_ik_solver:                0                               # if true (1) status of kdl ik solver will be printed
ik_vel_only:                    0                               # if true (1) after initialization we only use kdl ik velocity solver, no fk or ik position solvers
xyz_reached_threshold:          0.01                            # if cartesian position error of the gripper in robot-status is below this threshold position is considered reached
pos_reached_threshold:          0.05                            # if absolute position error for each of the joints in robot-status is below this threshold position is considered reached

##########################
# TRACKING MONITOR CONFIG
##########################

debug_state_par:                1                               # if true (1) state will be printed every time it changes
