whiskers_touched_max: 
    - max: 2.2
    - max: 2.2
    - max: 2.2
    - max: 2.2
    - max: 2.2
    - max: 2.2
    - max: 2.2
    - max: 2.2
    - max: 2.2
    - max: 2.2
    - max: 2.2
    - max: 2.2
