#ifndef LOGGINGINTERFACE_H
#define LOGGINGINTERFACE_H

#include <ros/ros.h>

#define     INFO_STREAM       ROS_INFO_STREAM
#define     WARNING_STREAM    ROS_WARN_STREAM
#define     ERROR_STREAM      ROS_ERROR_STREAM

#endif // LOGGINGINTERFACE_H
